### ISSUE TITLE
Some way to use `<Image/>` in Next.js? (Or this is redundant due to specific use)

### ISSUE THREAD

**Issue by kirillzhosul** [kirillzhosul/next-yandex-metrika#2]

**Comment by artginzburg** [comment]
This wouldn't make sense primarily because the `<img />` is only supposed to exist when JS is disabled.

Even if we assume that the `<noscript>` tag wasn't there:
1. Lazy loading is not relevant because the tracker needs to be loaded ASAP on visit (we would set this by specifying `priority` on the `<Image />`).
2. Size optimization is not relevant because the "pixel" is not really an image, and would not benefit in any way from size reduction. And if it was a real image — it's an external resource, making it much harder to optimize automatically.

Without these features, the Next.js `<Image />` is just a plain `<img />`.
